# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 148)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.tab)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.tab)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.dollars = QtWidgets.QLineEdit(parent=self.tab)
        self.dollars.setEnabled(False)
        self.dollars.setObjectName("dollars")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dollars)
        self.rubEdit = QtWidgets.QSpinBox(parent=self.tab)
        self.rubEdit.setMaximum(1000000000)
        self.rubEdit.setSingleStep(10)
        self.rubEdit.setObjectName("rubEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.rubEdit)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.pushButton = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.dolEdit = QtWidgets.QSpinBox(parent=self.tab_2)
        self.dolEdit.setMaximum(1000000000)
        self.dolEdit.setSingleStep(10)
        self.dolEdit.setObjectName("dolEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dolEdit)
        self.label_4 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.rubles = QtWidgets.QLineEdit(parent=self.tab_2)
        self.rubles.setEnabled(False)
        self.rubles.setObjectName("rubles")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.rubles)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.tab_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.pushButton_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Конвертер валют"))
        self.label.setText(_translate("Form", "Рублей"))
        self.label_2.setText(_translate("Form", "Долларов"))
        self.pushButton.setText(_translate("Form", "Перевести"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Рубли в доллары"))
        self.label_3.setText(_translate("Form", "Долларов"))
        self.label_4.setText(_translate("Form", "Рублей"))
        self.pushButton_2.setText(_translate("Form", "Перевести"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Доллары в рубли"))
